import Link from 'next/link';
import { CareersInvitation, Eyebrow, LatestWriting, TextLink } from '../components/ui';
import { ResearchTree } from '../components/visuals';
import { Arrow } from '../components/brand';
export default function Home() { return <>
  <section className="hero wrap"><div className="hero-copy"><p className="hero-kicker"><span className="live-dot" aria-hidden="true"/>Independent thinking. Systematic research.</p><h1><span className="line"><span>Rooted in curiosity.</span></span>{' '}<span className="line"><span>Driven by <em>evidence.</em></span></span></h1><p className="hero-lede">We bring scientific thinking to complex markets: asking better questions, finding deeper connections, and building understanding that lasts.</p><div className="hero-actions"><Link href="/our-research" className="button">Explore our research <Arrow/></Link><Link href="/who-we-are" className="hero-link">Who we are <Arrow/></Link></div></div><ResearchTree/><div className="hero-bottom"><ul className="hero-traits" aria-label="Our approach"><li><span>01</span>Quantitative</li><li><span>02</span>Systematic</li><li><span>03</span>Precise</li></ul><a href="#perspective" className="scroll-cue"><span className="scroll-cue-label">A deeper perspective</span><span className="scroll-cue-icon" aria-hidden="true"><span>↓</span></span></a></div></section>
  <section id="perspective" className="intro-section wrap"><Eyebrow>A considered approach</Eyebrow><div><h2>The world is complex.<br/>Our starting point is simple.<br/><span>Stay curious.</span></h2><div className="intro-detail"><p>Oak Field Research is a quantitative research firm working at the intersection of mathematics, technology, and financial markets.</p><p>We believe progress begins with an open mind—and earns its place through careful testing. Our work connects independent thought with the discipline of a systematic approach.</p><TextLink href="/who-we-are">Get to know Oak Field</TextLink></div></div></section>
  <section className="pillars-section"><div className="wrap"><div className="section-heading"><div><Eyebrow>How we think</Eyebrow><h2>Curiosity, with a method.</h2></div><p>Different disciplines.<br/>A shared commitment to understanding.</p></div><div className="pillar-grid">{[{ n: '01', title: 'Question deeply.', text: 'Look beyond the obvious. Start with first principles, challenge assumptions, and give good questions the attention they deserve.', symbol: 'question' }, { n: '02', title: 'Test rigorously.', text: 'Let evidence lead. Turn ideas into experiments, make uncertainty explicit, and learn as much from what fails as what works.', symbol: 'test' }, { n: '03', title: 'Build thoughtfully.', text: 'Bring research to life through precise engineering. Create systems that are clear, reproducible, and designed to keep learning.', symbol: 'build' }].map(p => <div className="pillar" key={p.n}><div className="pillar-top"><span>{p.n} /</span><div className={`pillar-symbol ${p.symbol}`} aria-hidden="true"><i/><i/><i/></div></div><h3>{p.title}</h3><p>{p.text}</p></div>)}</div><TextLink href="/our-research">Inside our research process</TextLink></div></section>
  <section className="technology-section"><div className="wrap technology-inner"><div className="engineering-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit orbit-three"/><div className="orbit-core">∑</div><span className="art-label label-one">IDEA</span><span className="art-label label-two">EXPERIMENT</span><span className="art-label label-three">UNDERSTANDING</span><div className="art-footnote">A CONTINUOUS EXCHANGE</div></div><div><Eyebrow>Research × engineering</Eyebrow><h2>Better together.<br/>By design.</h2><p>A good idea is only the beginning. Thoughtful infrastructure makes it possible to explore, challenge, and refine it.</p><p>We see research and engineering as one conversation. Each makes the other more capable.</p><TextLink href="/tech-blog" light>Explore our tech blog</TextLink></div></div></section>
  <LatestWriting/><CareersInvitation/>
  </>; }
