import { treeViewBox } from '../lib/research-tree';
function random(seed: number) { const x = Math.sin(seed * 127.1 + 311.7) * 43758.5453; return x - Math.floor(x); }
// The branches and leaves are thousands of shapes, so they load as two cached images (see lib/research-tree).
export function ResearchTree() {
  return <div className="tree-visual"><svg viewBox="0 0 600 510" role="img" aria-labelledby="tree-title"><title id="tree-title">A branching oak tree drawn from fine lines and thousands of data points</title><defs><pattern id="tree-grid" width="38" height="38" patternUnits="userSpaceOnUse"><path d="M38 0H0V38" fill="none" stroke="#1b5b40" strokeWidth=".4" opacity=".12"/></pattern><radialGradient id="tree-glow"><stop stopColor="#dfe8d9" stopOpacity=".8"/><stop offset="1" stopColor="#f6f7f0" stopOpacity="0"/></radialGradient></defs><circle cx="300" cy="252" r="245" fill="url(#tree-glow)"/><rect x="40" y="25" width="520" height="440" fill="url(#tree-grid)"/><g fill="none" stroke="#759482" strokeWidth=".6" opacity=".5"><circle cx="300" cy="252" r="202" strokeDasharray="2 7"/><path d="M300 10V476M33 252H570" strokeDasharray="2 6"/><ellipse cx="300" cy="432" rx="160" ry="24"/><ellipse cx="300" cy="432" rx="110" ry="15"/></g><image className="tree-branches" href="/research-tree/branches.svg" width={treeViewBox.width} height={treeViewBox.height}/><image className="tree-leaves" href="/research-tree/leaves.svg" width={treeViewBox.width} height={treeViewBox.height}/><g fill="#f8f9f3" stroke="#55745d" strokeWidth="1"><circle cx="300" cy="331" r="4"/><circle cx="191" cy="229" r="4"/><circle cx="401" cy="195" r="4"/></g><g fontSize="8" fill="#798878" fontFamily="monospace" letterSpacing="1.3"><text x="43" y="38">FIG. 01 — THE NATURE OF DISCOVERY</text><text x="383" y="486">ROOTED IN RESEARCH.</text><text x="43" y="486">OFR / 001</text></g><g fill="none" stroke="#7e927b" strokeWidth=".7"><path d="M35 65V55H45M555 55H565V65M35 437V447H45M555 447H565V437"/></g></svg><span className="visual-caption"><span className="live-dot"/><span><strong>Many observations.</strong>A deeper understanding.</span></span></div>;
}
export function ArticleVisual({ variant }: { variant: 'waves' | 'grid' | 'rings' }) {
  return <svg viewBox="0 0 600 330" className={`article-art art-${variant}`} aria-hidden="true" preserveAspectRatio="xMidYMid slice">{variant === 'rings' ? <g fill="none" stroke="currentColor" strokeWidth=".9">{Array.from({ length: 28 }, (_, i) => <ellipse key={i} cx={320 + Math.sin(i * .45) * 9} cy={164 + Math.cos(i * .7) * 4} rx={22 + i * 6.1} ry={19 + i * 4.5} transform={`rotate(${i * 3} 320 164)`}/>)}</g> : variant === 'grid' ? <g stroke="currentColor" fill="none" strokeWidth=".8">{Array.from({ length: 19 }, (_, i) => <path key={i} d={`M${80 + i * 22} 270L${190 + i * 13} 70M80 ${80 + i * 10}L500 ${110 + i * 10}`}/>)}<circle cx="300" cy="160" r="48" fill="var(--art-bg)"/><circle cx="300" cy="160" r="27"/><path d="M300 107V213M247 160H353"/></g> : <g stroke="currentColor" fill="none" strokeWidth=".8">{Array.from({ length: 25 }, (_, i) => <path key={i} d={`M-20 ${90 + i * 7} C100 ${250 + i * 3},160 ${-80 + i * 11},300 ${110 + i * 6} S470 ${310 - i * 9},620 ${100 + i * 5}`}/>)}</g>}<text x="25" y="306" fill="currentColor" opacity=".55" fontFamily="monospace" fontSize="9" letterSpacing="2">OAK FIELD / RESEARCH NOTES</text></svg>;
}

// A surface of offset sine curves over a field of data ticks, fading toward the right.
export function FooterWave() {
  const curve = (k: number) => Array.from({ length: 41 }, (_, i) => { const x = i * 22, fade = 1 - x / 1100; return `${i ? 'L' : 'M'}${x},${(118 + Math.sin(x / 105 - 1.1 + k * .16) * 46 * fade + k * 3.2 - x * .045).toFixed(1)}`; }).join('');
  const ticks = Array.from({ length: 34 }, (_, i) => ({ x: 14 + i * 17 + random(i) * 6, top: 60 + random(i + 40) * 70 }));
  return <svg className="footer-wave" viewBox="0 0 880 200" preserveAspectRatio="xMinYMax slice" aria-hidden="true"><defs><linearGradient id="footer-fade" x1="0" x2="1"><stop offset="0" stopColor="#fff"/><stop offset=".55" stopColor="#fff" stopOpacity=".55"/><stop offset="1" stopColor="#fff" stopOpacity="0"/></linearGradient><mask id="footer-mask"><rect width="880" height="200" fill="url(#footer-fade)"/></mask></defs><g mask="url(#footer-mask)"><g stroke="#6f9c82" strokeWidth=".6" opacity=".45">{ticks.map((t, i) => <path key={i} d={`M${t.x.toFixed(1)} ${t.top.toFixed(1)}V200`} strokeDasharray="1.5 4"/>)}</g><g fill="#a9cdb6">{ticks.map((t, i) => <circle key={i} cx={t.x.toFixed(1)} cy={t.top.toFixed(1)} r="1.2" opacity=".7"/>)}</g><g fill="none" stroke="#7fae93" strokeWidth=".7" opacity=".5">{Array.from({ length: 12 }, (_, k) => <path key={k} d={curve(k)}/>)}</g><path d={curve(-2)} fill="none" stroke="#dbeee1" strokeWidth="1.1" opacity=".8"/></g></svg>;
}

// Stands in for a portrait until an approved photo is supplied: growth rings, drawn differently for each card.
export function TeamArt({ seed }: { seed: number }) {
  const cx = 250 + (random(seed + 1) - .5) * 190, cy = 156 + (random(seed + 7) - .5) * 70, tilt = ((random(seed + 3) - .5) * 40).toFixed(1);
  return <svg className="team-art" viewBox="0 0 500 312" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><g fill="none" stroke="currentColor" strokeWidth=".8" transform={`rotate(${tilt} ${cx.toFixed(1)} ${cy.toFixed(1)})`}>{Array.from({ length: 18 }, (_, i) => { const r = 8 + i * 12 + random(seed * 19 + i) * 7; return <ellipse key={i} cx={(cx + Math.sin(i * .7 + seed) * 5).toFixed(1)} cy={(cy + Math.cos(i * .5 + seed) * 3).toFixed(1)} rx={(r * 1.18).toFixed(1)} ry={r.toFixed(1)} opacity={(.9 - i * .04).toFixed(2)}/>; })}</g><circle cx={cx.toFixed(1)} cy={cy.toFixed(1)} r="3" fill="#c69e3d"/></svg>;
}
