import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { ArticleListing, ResearchProcess } from '../../components/interactions';
import { CareersInvitation, Eyebrow, PageIntro, TextLink } from '../../components/ui';
import { ContactForm } from '../../components/contact-form';
const pages: Record<string, { label: string; title: string; description: string }> = {
  'who-we-are': { label: 'Who we are', title: 'Independent minds. Shared curiosity.', description: 'Oak Field Research is a quantitative research firm. Our starting point is a belief that complex questions deserve careful, collaborative thinking.' },
  'our-research': { label: 'Our research', title: 'Understanding begins with a question.', description: 'We connect mathematical thinking, empirical observation, and precise engineering. Our process is systematic. Our curiosity is open-ended.' },
  'tech-blog': { label: 'The tech blog', title: 'Under the surface.', description: 'Notes on the craft behind the research. Exploring data, experiments, and the systems that help ideas become useful.' },
  'news-insights': { label: 'News & insights', title: 'Notes from the field.', description: 'Ideas worth considering. Questions worth asking. A space for perspectives on research, technology, and the way we think.' },
  'join-our-team': { label: 'Join our team', title: 'Bring your curiosity.', description: 'Good research benefits from different ways of seeing. We welcome thoughtful people who enjoy working through difficult questions together.' },
  'enquiries': { label: 'Enquiries', title: 'Start a conversation.', description: 'A question, an idea, a different perspective. We would like to hear what is on your mind.' },
  'privacy': { label: 'Legal', title: 'Privacy notice.', description: 'Draft for company and legal review. This notice must be finalized before collecting personal information in production.' },
  'terms': { label: 'Legal', title: 'Terms of use.', description: 'Draft for legal review. The company’s legal entity, governing law, and final terms have not yet been supplied.' },
  'disclosures': { label: 'Legal', title: 'Disclosures.', description: 'Information about the scope of this website and its illustrative content.' },
};
export function generateStaticParams() { return Object.keys(pages).map(section => ({ section })); }
export async function generateMetadata({ params }: { params: Promise<{ section: string }> }): Promise<Metadata> { const { section } = await params; const page = pages[section]; return { title: page?.label === 'Legal' ? page.title : page?.label, description: page?.description, alternates: { canonical: `/${section}` } }; }
export default async function SectionPage({ params }: { params: Promise<{ section: string }> }) {
  const { section } = await params; const intro = pages[section]; if (!intro) notFound();
  return <><PageIntro {...intro}/>{section === 'who-we-are' && <><section className="content-section wrap split-section"><div><Eyebrow>Our perspective</Eyebrow><h2>Open to ideas.<br/>Accountable to evidence.</h2></div><div className="body-copy"><p>Our approach brings together the habits of scientific research and the craft of engineering: ask a precise question, study the evidence, and make what we learn reproducible.</p><p>We value clarity over complexity for its own sake. A useful idea should be explainable, testable, and open to revision. Progress comes from the quality of the conversation as much as the sophistication of the method.</p><TextLink href="/our-research">See how we think</TextLink></div></section><section id="principles" className="content-section wrap"><Eyebrow>Principles we work by</Eyebrow><div className="principles">{[['Intellectual honesty.','Make assumptions visible. Be clear about what is known, what is uncertain, and what would change our view.'],['Collective understanding.','Share context, welcome constructive disagreement, and make space for ideas from different disciplines.'],['Care in the details.','Treat reproducibility, clear communication, and thoughtful engineering as part of the research itself.']].map(([title,text],i) => <div key={title}><span className="quiet-number">0{i+1}</span><h3>{title}</h3><p>{text}</p></div>)}</div></section><section id="people" className="content-section wrap split-section"><div><Eyebrow>The people behind the questions</Eyebrow><h2>Different disciplines.<br/>One conversation.</h2></div><div><p className="intro-description">Research grows when mathematics, data, and engineering meet. This space will introduce the people and perspectives behind Oak Field.</p><div className="note-panel team-placeholder"><span aria-hidden="true">↗</span><div><h3>Our team, in their own words.</h3><p>Team profiles, biographies, company history, and locations will be added once verified and approved.</p></div></div></div></section><CareersInvitation/></>}
  {section === 'our-research' && <><section className="content-section wrap"><div className="section-heading"><div><Eyebrow>A continuous process</Eyebrow><h2>From an observation<br/>to a better understanding.</h2></div><p>Select a stage to explore our approach.</p></div><ResearchProcess/></section><section className="content-section wrap split-section"><div><Eyebrow>Built on careful foundations</Eyebrow><h2>Precision is a practice.</h2></div><div className="body-copy"><p>Data quality, sound evaluation, and reproducibility are part of the same discipline. We consider how an observation was collected, what assumptions a model makes, and how conclusions behave beyond their original setting.</p><p>This is an overview of our research philosophy. Specific strategies, assets, proprietary methods, and performance are not disclosed here.</p><TextLink href="/tech-blog">Read our engineering notes</TextLink></div></section><CareersInvitation/></>}
  {(section === 'tech-blog' || section === 'news-insights') && <ArticleListing section={section}/>}
  {section === 'join-our-team' && <><section className="content-section wrap split-section"><div><Eyebrow>Work with intention</Eyebrow><h2>Space to think.<br/>People to think with.</h2></div><div className="body-copy"><p>We value people who can ask a clear question, listen carefully, and explain how they arrived at an answer. A willingness to revise an idea matters as much as the confidence to propose it.</p><p>Research and engineering are closely connected here. The problems we care about benefit from a range of disciplines and a shared respect for careful work.</p></div></section><section className="content-section wrap"><Eyebrow>Areas of interest</Eyebrow><h2 style={{marginTop:20}}>Where disciplines meet.</h2><div className="role-list">{[['Quantitative research','Mathematical reasoning, statistical thinking, and the design of thoughtful experiments.'],['Research engineering','Reproducible tooling, dependable systems, and the connection between ideas and implementation.'],['Data & infrastructure','Careful data foundations, clear interfaces, and systems that make research easier to inspect.']].map(([title,text]) => <div key={title} className="role-row"><h3>{title}</h3><p>{text}</p></div>)}</div><div className="note-panel"><h3>A future conversation.</h3><p>No specific vacancies are currently published. The disciplines above describe areas of interest, not open positions. You are welcome to introduce yourself for future consideration.</p><div style={{marginTop:22}}><TextLink href="/enquiries?category=careers">Send a general expression of interest</TextLink></div></div></section><section className="content-section wrap"><Eyebrow>Getting to know each other</Eyebrow><h2 style={{marginTop:20}}>A thoughtful exchange.</h2><p className="diagram-caption">An indicative process; the stages for any future role will be shared with candidates.</p><div className="hiring-steps">{[['A first conversation','An exchange about your interests, experience, and the questions you enjoy working on.'],['Explore your thinking','A discussion of relevant work and how you reason through a problem.'],['Meet the people','Time to understand each other’s working styles and ask questions about the role.']].map(([title,text],i) => <div key={title}><span className="quiet-number">0{i+1} /</span><h3>{title}</h3><p>{text}</p></div>)}</div></section></>}
  {section === 'enquiries' && <section className="wrap contact-layout"><aside><h2>Where shall we begin?</h2><p>Choose the subject that best fits your enquiry so it can reach the right conversation.</p><div className="contact-categories">{[['General','Questions about Oak Field Research.'],['Research collaboration','Shared questions and thoughtful exchange.'],['Media','Editorial and press enquiries.'],['Careers','Introduce yourself and your interests.']].map(([title,text]) => <div key={title}><strong>{title}</strong><p>{text}</p></div>)}</div>{!process.env.CONTACT_WEBHOOK_URL && <p className="form-notice" style={{marginTop:25}}>Enquiry delivery is not yet configured. The form will let you know if your message cannot be sent.</p>}</aside><ContactForm/></section>}
  {['privacy','terms','disclosures'].includes(section) && <section className="wrap legal-content">{section === 'privacy' ? <><h2>Information you choose to share</h2><p>The enquiry form requests a name, email address, enquiry category, message, and an optional organization. Once delivery is configured, these details are sent to the company’s chosen enquiry service to respond to your request.</p><h2>Before launch</h2><p>The responsible legal entity, privacy contact, service providers, retention periods, applicable rights, and international data transfers must be specified and approved. Do not enable enquiry delivery until this notice is complete.</p><h2>Technical information</h2><p>This implementation does not add advertising cookies or analytics. The hosting provider may process technical request logs. Hosting details and any future analytics or cookies must be documented before use.</p></> : section === 'terms' ? <><h2>About this website</h2><p>This website introduces a research philosophy and contains illustrative editorial material. It is not intended to provide investment advice or an offer to buy or sell financial instruments.</p><h2>Terms to be finalized</h2><p>Legal entity details, intellectual property terms, permitted use, liability provisions, governing law, and dispute resolution are pending legal review. This page is a working placeholder and does not represent approved company terms.</p></> : <><h2>Research, presented in context</h2><p>Diagrams and illustrations communicate general research concepts. They do not show live market data, actual strategies, returns, or investment performance.</p><h2>Illustrative editorial content</h2><p>Articles marked “Illustrative article” are sample writing for this website. Their dates and reading times are editorial examples. They are not verified company announcements or records of proprietary work.</p><h2>Company information</h2><p>No assets under management, performance, regulatory status, partnerships, or office locations are represented. The oak symbol is a temporary vector brand interpretation, pending an approved identity asset.</p></>}</section>}
  </>;
}
