function random(seed: number) { const x = Math.sin(seed * 127.1 + 311.7) * 43758.5453; return x - Math.floor(x); }
export function ResearchTree() {
  const branches: { d: string; width: number }[] = [];
  const leaves: { x: number; y: number; r: number; opacity: number }[] = [];
  function branch(x: number, y: number, length: number, angle: number, depth: number, seed: number) {
    const endX = x + Math.cos(angle) * length, endY = y + Math.sin(angle) * length;
    branches.push({ d: `M${x.toFixed(2)},${y.toFixed(2)} Q${(x + Math.cos(angle + .12) * length * .55).toFixed(2)},${(y + Math.sin(angle + .12) * length * .55).toFixed(2)} ${endX.toFixed(2)},${endY.toFixed(2)}`, width: depth * .48 + .2 });
    if (depth <= 3) for (let i = 0; i < 15; i++) { const t = random(seed + i * 7), a = random(seed + i * 9 + 8) * Math.PI * 2, spread = 9 + depth * 5; leaves.push({ x: endX + Math.cos(a) * spread * t, y: endY + Math.sin(a) * spread * t, r: .65 + random(seed + i * 3) * 1.6, opacity: .22 + random(seed + i) * .65 }); }
    if (depth === 0) return;
    branch(endX, endY, length * (.7 + random(seed) * .11), angle - .32 - random(seed + 1) * .37, depth - 1, seed * 2 + 1);
    branch(endX, endY, length * (.68 + random(seed + 2) * .13), angle + .3 + random(seed + 3) * .36, depth - 1, seed * 2 + 2);
  }
  branch(300, 425, 95, -Math.PI / 2, 8, 7);
  return <div className="tree-visual"><svg viewBox="0 0 600 510" role="img" aria-labelledby="tree-title"><title id="tree-title">A branching oak tree drawn from fine lines and thousands of data points</title><defs><pattern id="tree-grid" width="38" height="38" patternUnits="userSpaceOnUse"><path d="M38 0H0V38" fill="none" stroke="#1b5b40" strokeWidth=".4" opacity=".12"/></pattern><radialGradient id="tree-glow"><stop stopColor="#dfe8d9" stopOpacity=".8"/><stop offset="1" stopColor="#f6f7f0" stopOpacity="0"/></radialGradient></defs><circle cx="300" cy="252" r="245" fill="url(#tree-glow)"/><rect x="40" y="25" width="520" height="440" fill="url(#tree-grid)"/><g fill="none" stroke="#759482" strokeWidth=".6" opacity=".5"><circle cx="300" cy="252" r="202" strokeDasharray="2 7"/><path d="M300 10V476M33 252H570" strokeDasharray="2 6"/><ellipse cx="300" cy="432" rx="160" ry="24"/><ellipse cx="300" cy="432" rx="110" ry="15"/></g><g className="tree-branches" fill="none" stroke="#365e44" strokeLinecap="round">{branches.map((b, i) => <path key={i} d={b.d} strokeWidth={b.width}/>)}</g><g className="tree-leaves" fill="#406d4b">{leaves.map((l, i) => <circle key={i} cx={l.x} cy={l.y} r={l.r} opacity={l.opacity}/>)}</g><g fill="#f8f9f3" stroke="#55745d" strokeWidth="1"><circle cx="300" cy="331" r="4"/><circle cx="191" cy="229" r="4"/><circle cx="401" cy="195" r="4"/></g><g fontSize="8" fill="#798878" fontFamily="monospace" letterSpacing="1.3"><text x="43" y="38">FIG. 01 — THE NATURE OF DISCOVERY</text><text x="383" y="486">ROOTED IN RESEARCH.</text><text x="43" y="486">OFR / 001</text></g><g fill="none" stroke="#7e927b" strokeWidth=".7"><path d="M35 65V55H45M555 55H565V65M35 437V447H45M555 447H565V437"/></g></svg><span className="visual-caption"><span className="live-dot"/> Many observations. A deeper understanding.</span></div>;
}
export function ArticleVisual({ variant }: { variant: 'waves' | 'grid' | 'rings' }) {
  return <svg viewBox="0 0 600 330" className={`article-art art-${variant}`} aria-hidden="true" preserveAspectRatio="xMidYMid slice">{variant === 'rings' ? <g fill="none" stroke="currentColor" strokeWidth=".9">{Array.from({ length: 28 }, (_, i) => <ellipse key={i} cx={320 + Math.sin(i * .45) * 9} cy={164 + Math.cos(i * .7) * 4} rx={22 + i * 6.1} ry={19 + i * 4.5} transform={`rotate(${i * 3} 320 164)`}/>)}</g> : variant === 'grid' ? <g stroke="currentColor" fill="none" strokeWidth=".8">{Array.from({ length: 19 }, (_, i) => <path key={i} d={`M${80 + i * 22} 270L${190 + i * 13} 70M80 ${80 + i * 10}L500 ${110 + i * 10}`}/>)}<circle cx="300" cy="160" r="48" fill="var(--art-bg)"/><circle cx="300" cy="160" r="27"/><path d="M300 107V213M247 160H353"/></g> : <g stroke="currentColor" fill="none" strokeWidth=".8">{Array.from({ length: 25 }, (_, i) => <path key={i} d={`M-20 ${90 + i * 7} C100 ${250 + i * 3},160 ${-80 + i * 11},300 ${110 + i * 6} S470 ${310 - i * 9},620 ${100 + i * 5}`}/>)}</g>}<text x="25" y="306" fill="currentColor" opacity=".55" fontFamily="monospace" fontSize="9" letterSpacing="2">OAK FIELD / RESEARCH NOTES</text></svg>;
}

// A surface of offset sine curves over a field of data ticks, fading toward the right.
export function FooterWave() {
  const curve = (k: number) => Array.from({ length: 41 }, (_, i) => { const x = i * 22, fade = 1 - x / 1100; return `${i ? 'L' : 'M'}${x},${(118 + Math.sin(x / 105 - 1.1 + k * .16) * 46 * fade + k * 3.2 - x * .045).toFixed(1)}`; }).join('');
  const ticks = Array.from({ length: 34 }, (_, i) => ({ x: 14 + i * 17 + random(i) * 6, top: 60 + random(i + 40) * 70 }));
  return <svg className="footer-wave" viewBox="0 0 880 200" preserveAspectRatio="xMinYMax slice" aria-hidden="true"><defs><linearGradient id="footer-fade" x1="0" x2="1"><stop offset="0" stopColor="#fff"/><stop offset=".55" stopColor="#fff" stopOpacity=".55"/><stop offset="1" stopColor="#fff" stopOpacity="0"/></linearGradient><mask id="footer-mask"><rect width="880" height="200" fill="url(#footer-fade)"/></mask></defs><g mask="url(#footer-mask)"><g stroke="#6f9c82" strokeWidth=".6" opacity=".45">{ticks.map((t, i) => <path key={i} d={`M${t.x.toFixed(1)} ${t.top.toFixed(1)}V200`} strokeDasharray="1.5 4"/>)}</g><g fill="#a9cdb6">{ticks.map((t, i) => <circle key={i} cx={t.x.toFixed(1)} cy={t.top.toFixed(1)} r="1.2" opacity=".7"/>)}</g><g fill="none" stroke="#7fae93" strokeWidth=".7" opacity=".5">{Array.from({ length: 12 }, (_, k) => <path key={k} d={curve(k)}/>)}</g><path d={curve(-2)} fill="none" stroke="#dbeee1" strokeWidth="1.1" opacity=".8"/></g></svg>;
}
